name: dotnet

on:
  push:
    paths:
      - ".github/workflows/dotnet.yml"
      - "dotnet/**"
  workflow_dispatch: # manual

jobs:
  build:
    name: build-dotnet-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
        working-directory: dotnet
      - run: dotnet test
        working-directory: ./dotnet



# *** notes:
# steps[*].working-directory: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory
# path filter globs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
