name: go-image
on:
  push:
    paths:
      - ".github/workflows/go-image.yml"
      - "go/**"
  workflow_dispatch: # manual
permissions:
  packages: write
  contents: read # not needed in public repos
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: pwd && ls -al
      - run: docker image build -t upper .
        working-directory: ./go
      - run: pwd && ls -al
      - name: test it
        run: docker container run upper hello wes

