name: go-image
on:
  push:
    paths:
      - ".github/workflows/go-image.yml"
      - "go/**"
  workflow_dispatch: # manual
permissions:
  packages: write
  contents: read # not needed in public repos
jobs:
  image:
    runs-on: ubuntu-latest
    env:
      GH_USER: ${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: docker image build -t upper .
        working-directory: ./go
      - name: test it
        run: docker container run upper hello wes
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GH_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag upper ghcr.io/${{ env.GH_USER }}/upper:latest
      - run: docker tag upper ghcr.io/${{ env.GH_USER }}/upper:${{ github.ref_name }}
      - run: docker push ghcr.io/${{ env.GH_USER }}/upper:latest
      - run: docker push ghcr.io/${{ env.GH_USER }}/upper:${{ github.ref_name }}

