name: go
on:
  push:
    paths:
      - ".github/workflows/go.yml"
      - "go/**"
  workflow_dispatch: # manual
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: go
    steps:
      # - run: pwd && ls -al # linux specific command
      - uses: actions/checkout@v4
      # - run: pwd && ls -al # linux specific command
      - uses: actions/setup-go@v5
        with:
          # go-version: '1.22'
          go-version-file: ./go/go.mod
          cache-dependency-path: ./go/go.sum
      # - run: go mod download
      - run: go version
      - run: ls
      - run: go build
      - run: ls
      - run: go test -v
      - uses: actions/upload-artifact@v4
        with:
          path: ./go/upper*
          name: "build-${{ matrix.os }}"