name: go

on:
  push:
    paths:
      - ".github/workflows/go.yml"
      - "go/**"
  workflow_dispatch: # manual

jobs:
  build:
    strategy:
      matrix:
       os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
    steps:
      - run: pwd && ls -al
      - uses: actions/checkout@v4
      - run: pwd && ls -al
      # - run: go version
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          # go-version-file: ./go/go.mod
          cache-dependency-path: ./go/go.sum
      - run: go mod download
        working-directory: go
      - run: ls
        working-directory: go
      - run: go build
        working-directory: go
      - run: ls
        working-directory: go
      - run: go test -v
        working-directory: go
        name: build-and-test
      - uses: actions/upload-artifact@v4
        with:
          path: ./go/go
          name: "build-${{ matrix.os }}"