name: hello-world
# run-name: ${{ github.actor }}
on: [push]
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "actor - ${{ github.actor }}"
      - run: echo "event - ${{ github.event_name }}"
      - run: echo "os - ${{ runner.os }}"
      - run: echo "branch - ${{ github.ref }}, repository - ${{ github.repository }}"
      - name: check-out-repository-code
        uses: actions/checkout@v4
      - run: echo "repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: echo
        run: echo "$(cat node/hello_world.txt)"
      - run: echo "status - ${{ job.status }}."
