name: hello-world
# run-name: ${{ github.actor }}
on: 
  push:
    paths:
      - ".github/workflows/hello-world.yml"
  workflow_dispatch: # manual
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "actor - ${{ github.actor }}
          event - ${{ github.event_name }}
          os - ${{ runner.os }}
          branch - ${{ github.ref }}
          repository - ${{ github.repository }}"
      - uses: actions/checkout@v4
      - run: echo "repository has been cloned to the runner."
      - run: ls ${{ github.workspace }}
      - run: echo "$(cat readme.md)"
      - run: echo "status - ${{ job.status }}."
