name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "$(cat node/hello_world.txt)"
      - name: check-out-repository-code
        uses: actions/checkout@v4
