name: test

on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "go/**"
  workflow_dispatch: # manual

jobs:
  capture:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: go
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache-dependency-path: ./go/go.sum
      - run: ls
      - run: go build
      - run: ls
      - run: go test -v
      - uses: actions/upload-artifact@v4
        with:
          path: ./go/go*
          name: "build-${{ matrix.os }}"
